"""Type stubs for the ``ogentic_audit`` package.

Records are exposed as ``dict[str, Any]`` rather than dataclasses; see the
``Record`` TypedDict below for the dict's required shape. The choice is
documented in OGE-433 (PyO3 binding ticket).
"""

from __future__ import annotations

from types import TracebackType
from typing import Any, TypedDict

__version__: str

def format_version() -> int: ...
def core_version() -> str: ...

class KeyHandle:
    """A reference to the signing key. The handle never exposes raw bytes."""

    @staticmethod
    def from_bytes(bytes: bytes) -> KeyHandle: ...
    @staticmethod
    def from_hex(hex_str: str) -> KeyHandle: ...
    @staticmethod
    def from_env(var_name: str = "OGENTIC_AUDIT_KEY_HEX") -> KeyHandle: ...
    @staticmethod
    def from_keychain(service: str, account: str = "default") -> KeyHandle: ...
    def key_id_hex(self) -> str: ...

class Record(TypedDict):
    """The dict shape every iterator and seek call returns."""

    segment_index: int
    record_id: int
    ts_wall: str
    ts_mono_delta: int
    session_id_hex: str
    actor: str
    event: str
    payload: dict[str, Any]
    key_id_hex: str
    schema_version: int
    prev_hash: bytes
    prev_hash_hex: str
    hmac: bytes
    hmac_hex: str

class Writer:
    @staticmethod
    def open(
        log_dir: str,
        key: KeyHandle,
        session_id_hex: str = "00000000000000000000000000000000",
        segment_size_bytes: int | None = None,
    ) -> Writer: ...
    def append(self, record: dict[str, Any]) -> int: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Writer: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def recovery_action(self) -> str: ...
    def recovery_truncated_bytes(self) -> int: ...

class RecordIter:
    def __iter__(self) -> RecordIter: ...
    def __next__(self) -> Record: ...

class Reader:
    @staticmethod
    def open(log_dir: str) -> Reader: ...
    def segments(self) -> list[int]: ...
    def __iter__(self) -> RecordIter: ...

class VerifyReport:
    ok: bool
    compact: str
    verdict_kind: str
    log_dir: str
    key_id_hex: str
    segments_inspected: int
    records_inspected: int
    final_hmac_hex: str | None
    violation: dict[str, Any] | None
    additional_violations: list[dict[str, Any]]

def verify(
    log_dir: str,
    key: KeyHandle,
    forensic: bool = False,
    raise_on_violation: bool = False,
) -> VerifyReport: ...

# Exception hierarchy.
class OgenticAuditError(Exception): ...
class IoFailure(OgenticAuditError): ...
class ArgumentError(OgenticAuditError): ...
class RecoveryError(OgenticAuditError): ...
class VerificationFailed(OgenticAuditError): ...
class ChainBreakError(VerificationFailed): ...
class HmacMismatchError(VerificationFailed): ...
class MissingRecordError(VerificationFailed): ...
class RecordCorruptError(VerificationFailed): ...
class HeaderCorruptError(VerificationFailed): ...
class KeyIdMismatchError(VerificationFailed): ...
class SegmentDiscontinuityError(VerificationFailed): ...
class TimestampError(VerificationFailed): ...
class SchemaError(VerificationFailed): ...
