//! Conformance against `tests/vectors/v0.2` (spec v0.2 §16), generated by
//! `tools/gen_vectors_v02.py` with Python `cryptography` — an
//! implementation independent of this crate.
//!
//! - writer vectors are rebuilt byte for byte from `inputs.json`;
//! - every run in every `inputs.json` is executed through the library
//!   and must produce the expected verdict, reason and exit code;
//! - the Ed25519 edge cases, Appendix A fingerprints, the release builder
//!   and the 0.3.x behaviour on a signed log are checked against the
//!   committed files.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};

use ogentic_audit_core::signed::{
    ed25519, hex, unhex, verify_release, visit_records, AttestationBuilder, FileSpec,
    InMemorySigner, LogSpec, Part, PublicKey, ReleaseOptions, Scope, SignedVerifier,
    SignedVerifyOptions, SignedWriter, SuppliedCheckpoint, TrustContext,
};
use ogentic_audit_core::{InMemoryKey, PayloadValue, RecordInput, Verdict, Verifier, WriterConfig};
use serde_json::Value as J;
use sha2::{Digest, Sha256};

fn vectors_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/vectors/v0.2")
}

fn inputs(dir: &Path) -> J {
    serde_json::from_str(&std::fs::read_to_string(dir.join("inputs.json")).unwrap()).unwrap()
}

fn all_vectors() -> Vec<PathBuf> {
    let mut v: Vec<PathBuf> = std::fs::read_dir(vectors_dir())
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| p.is_dir())
        .collect();
    v.sort();
    assert!(
        v.len() >= 90,
        "expected the v0.2 vector suite, found {}",
        v.len()
    );
    v
}

fn test_nonce(log_id: &[u8; 16], i: u64) -> [u8; 32] {
    let mut data = log_id.to_vec();
    data.extend_from_slice(&i.to_be_bytes());
    ogentic_audit_core::signed::th("ogentic-audit/v0.2/test-nonce", &data)
}

fn payload(v: &J) -> BTreeMap<String, PayloadValue> {
    v.as_object()
        .unwrap()
        .iter()
        .map(|(k, v)| {
            let pv = match v {
                J::Number(n) => PayloadValue::Uint(n.as_u64().unwrap()),
                J::String(s) => PayloadValue::Text(s.clone()),
                other => panic!("unsupported payload value {other}"),
            };
            (k.clone(), pv)
        })
        .collect()
}

#[test]
fn writer_vectors_rebuild_byte_for_byte() {
    let mut n = 0;
    for dir in all_vectors() {
        let inp = inputs(&dir);
        let Some(w) = inp.get("writer") else { continue };
        n += 1;
        let key = w["key"].as_str().unwrap();
        let seed = inp["keys"][key]["seed"].as_str().unwrap();
        let log_id: [u8; 16] = unhex(w["log_id"].as_str().unwrap()).unwrap();
        let session: [u8; 16] = unhex(w["session_id"].as_str().unwrap()).unwrap();
        let tmp = tempfile::tempdir().unwrap();
        let counter = Arc::new(Mutex::new(0u64));
        let c2 = counter.clone();
        let cfg = WriterConfig {
            segment_size_bytes: w["segment_size_bytes"].as_u64().unwrap(),
            ..WriterConfig::default()
        };
        let mut writer = SignedWriter::create_with_log_id(
            tmp.path(),
            Box::new(InMemorySigner::from_seed(unhex(seed).unwrap())),
            session,
            cfg,
            log_id,
        )
        .unwrap()
        .with_nonce_source(move || {
            let mut i = c2.lock().unwrap();
            let nonce = test_nonce(&log_id, *i);
            *i += 1;
            nonce
        });
        for r in w["records"].as_array().unwrap() {
            writer
                .append(RecordInput {
                    ts_wall: r["ts_wall"].as_str().unwrap().into(),
                    ts_mono_delta: r["ts_mono_delta"].as_u64().unwrap(),
                    actor: r["actor"].as_str().unwrap().into(),
                    event: r["event"].as_str().unwrap().into(),
                    payload: payload(&r["payload"]),
                    schema_version: r["schema_version"].as_u64().unwrap() as u8,
                })
                .unwrap();
        }
        if w["seal"].as_bool().unwrap() {
            writer.seal().unwrap();
        }
        writer.flush().unwrap();
        drop(writer);
        let mut expected: Vec<String> = std::fs::read_dir(dir.join("log"))
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        expected.sort();
        let mut got: Vec<String> = std::fs::read_dir(tmp.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        got.sort();
        assert_eq!(got, expected, "{}: segment files", dir.display());
        for f in &expected {
            let a = std::fs::read(dir.join("log").join(f)).unwrap();
            let b = std::fs::read(tmp.path().join(f)).unwrap();
            assert!(
                a == b,
                "{}: {f} differs from the writer's output",
                dir.display()
            );
        }
        // chain.json agrees with what a reader sees.
        let chain: J =
            serde_json::from_str(&std::fs::read_to_string(dir.join("chain.json")).unwrap())
                .unwrap();
        let mut hashes = Vec::new();
        visit_records(dir.join("log"), |r| {
            hashes.push(hex(&r.record_hash));
            true
        })
        .unwrap();
        let want: Vec<String> = chain["records"]
            .as_array()
            .unwrap()
            .iter()
            .map(|r| r["record_hash"].as_str().unwrap().to_string())
            .collect();
        assert_eq!(hashes, want, "{}: chain.json", dir.display());
    }
    assert!(n >= 6);
}

/// Outcome of one run through the library.
#[derive(Debug, Default)]
struct Outcome {
    exit: u8,
    verdict: String,
    reason: Option<String>,
    error: String,
    head_anchored: Option<bool>,
    elided: Vec<String>,
    warnings: Vec<String>,
    witnesses: Vec<String>,
    records_after_head: Option<u64>,
    ignored: Vec<String>,
    trust_path: Vec<String>,
    authentication: Option<String>,
}

fn trust_for(dir: &Path, r: &J) -> Result<TrustContext, String> {
    let mut t = TrustContext::new();
    if let Some(pk) = r.get("public_key").and_then(J::as_str) {
        let key = PublicKey::parse(pk).map_err(|e| e.to_string())?;
        t.pin_key(key, None, Scope::DEFAULT)
            .map_err(|e| e.to_string())?;
    }
    for f in r
        .get("key_fingerprint")
        .and_then(J::as_array)
        .into_iter()
        .flatten()
    {
        t.pin(f.as_str().unwrap(), None, Scope::DEFAULT)
            .map_err(|e| e.to_string())?;
    }
    if let Some(tf) = r.get("trust").and_then(J::as_str) {
        t.add_allowed_signers(&std::fs::read_to_string(dir.join(tf)).unwrap())
            .map_err(|e| e.to_string())?;
    }
    let operator = r.get("statements_source").and_then(J::as_str) != Some("bundle");
    for s in r
        .get("statements")
        .and_then(J::as_array)
        .into_iter()
        .flatten()
    {
        t.add_statements(&dir.join(s.as_str().unwrap()), operator)
            .map_err(|e| e.to_string())?;
    }
    for f in r
        .get("revocations")
        .and_then(J::as_array)
        .into_iter()
        .flatten()
    {
        t.add_revocation(&dir.join(f.as_str().unwrap()))
            .map_err(|e| e.to_string())?;
    }
    Ok(t)
}

fn strs(v: &J) -> Vec<String> {
    v.as_array()
        .map(|a| {
            a.iter()
                .map(|x| x.as_str().unwrap_or_default().to_string())
                .collect()
        })
        .unwrap_or_default()
}

fn exit_of(v: Verdict) -> u8 {
    match v {
        Verdict::Verified => 0,
        Verdict::SelfConsistent => 4,
        _ => 1,
    }
}

fn run_library(dir: &Path, r: &J) -> Outcome {
    let cmd = r["command"].as_str().unwrap();
    let target = dir.join(r["target"].as_str().unwrap());
    let mut o = Outcome::default();
    if cmd == "v01-verifier" {
        let key: [u8; 32] = unhex(r["hmac_key_hex"].as_str().unwrap()).unwrap();
        let rep = Verifier::new(Box::new(InMemoryKey::from_bytes(key)))
            .verify(&target)
            .unwrap();
        o.exit = exit_of(rep.verdict);
        o.verdict = rep.compact_verdict();
        return o;
    }
    if r.get("hmac_key_source").is_some() || r.get("env").is_some() {
        // HMAC key handling is a CLI concern (explicit key source); the
        // library side is the format check.
        let fmt = ogentic_audit_core::signed::log_format(&target)
            .unwrap()
            .unwrap();
        let explicit = r.get("hmac_key_source").is_some();
        let pinned = r.get("key_fingerprint").is_some() || r.get("public_key").is_some();
        if fmt == 1 && explicit && !pinned {
            let hexkey = r["env"]["OGENTIC_AUDIT_KEY_HEX"].as_str().unwrap();
            let rep = Verifier::new(Box::new(InMemoryKey::from_bytes(unhex(hexkey).unwrap())))
                .verify(&target)
                .unwrap();
            o.exit = exit_of(rep.verdict);
            o.verdict = rep.compact_verdict();
            o.authentication = Some("shared-key".into());
        } else {
            o.exit = 3;
        }
        return o;
    }
    let trust = match trust_for(dir, r) {
        Ok(t) => t,
        Err(e) => {
            o.exit = 3;
            o.error = e;
            return o;
        },
    };
    match cmd {
        "verify" => {
            let mut opts = SignedVerifyOptions::new().forensic(r.get("segment").is_some());
            for c in r
                .get("checkpoints")
                .and_then(J::as_array)
                .into_iter()
                .flatten()
            {
                let mut sc = SuppliedCheckpoint::load(&dir.join(c.as_str().unwrap())).unwrap();
                for w in r
                    .get("witnesses")
                    .and_then(J::as_array)
                    .into_iter()
                    .flatten()
                {
                    sc.add_witness(&dir.join(w.as_str().unwrap())).unwrap();
                }
                opts = opts.checkpoint(sc);
            }
            if let Some(id) = r.get("expect_log_id").and_then(J::as_str) {
                opts = opts.expect_log_id(unhex(id).unwrap());
            }
            match SignedVerifier::new(trust).verify_with_options(&target, opts) {
                Ok(mut rep) => {
                    if let Some(s) = r.get("segment").and_then(J::as_u64) {
                        rep = rep.filter_segment(s as u16);
                    }
                    o.exit = exit_of(rep.verdict);
                    o.verdict = rep.compact_verdict();
                    o.reason = rep
                        .violation()
                        .and_then(|v| v.reason.clone())
                        .or_else(|| rep.not_verified_reason.map(|r| r.as_str().to_string()));
                    o.head_anchored = Some(rep.log.head_anchored);
                    o.elided = rep
                        .log
                        .elided_records
                        .iter()
                        .map(|(s, r)| format!("s{s}r{r}"))
                        .collect();
                    o.warnings = rep.warnings.iter().map(|w| w.kind.clone()).collect();
                    o.witnesses = rep
                        .checkpoints
                        .iter()
                        .flat_map(|c| c.witnesses.iter().map(|w| w.principal.clone()))
                        .collect();
                    o.trust_path = rep
                        .signer
                        .as_ref()
                        .map(|s| s.trust_path.iter().map(|k| k.to_grouped_hex()).collect())
                        .unwrap_or_default();
                },
                Err(e) => {
                    o.exit = e.exit_code();
                    o.error = format!("{e:?}");
                },
            }
        },
        "verify-release" => {
            let mut opts = ReleaseOptions::new().allow_unattested(
                r.get("allow_unattested")
                    .and_then(J::as_bool)
                    .unwrap_or(false),
            );
            if let Some(id) = r.get("expect_release_id").and_then(J::as_str) {
                opts = opts.expect_release_id(id);
            }
            match verify_release(&target, &trust, &opts) {
                Ok(rep) => {
                    o.exit = exit_of(rep.verdict);
                    o.verdict = rep.compact_verdict();
                    o.reason = rep
                        .violations
                        .first()
                        .and_then(|v| v.reason.clone())
                        .or_else(|| rep.not_verified_reason.map(|r| r.as_str().to_string()));
                    o.warnings = rep.warnings.iter().map(|w| w.kind.clone()).collect();
                    o.ignored = rep.ignored.clone();
                    let logs: Vec<_> = rep.logs.iter().filter_map(|l| l.report.as_ref()).collect();
                    o.elided = logs
                        .iter()
                        .flat_map(|l| {
                            l.log
                                .elided_records
                                .iter()
                                .map(|(s, r)| format!("s{s}r{r}"))
                        })
                        .collect();
                    o.records_after_head =
                        Some(logs.iter().map(|l| l.log.records_after_head).sum());
                },
                Err(e) => {
                    o.exit = e.exit_code();
                    o.error = e.to_string();
                },
            }
        },
        other => panic!("unknown command {other}"),
    }
    o
}

fn check(name: &str, r: &J, o: &Outcome) {
    let e = &r["expect"];
    let ctx = format!(
        "{name}/{}: {o:?}",
        r.get("name").and_then(J::as_str).unwrap_or("run")
    );
    assert_eq!(u64::from(o.exit), e["exit"].as_u64().unwrap(), "exit {ctx}");
    if let Some(v) = e.get("verdict").and_then(J::as_str) {
        assert_eq!(o.verdict, v, "verdict {ctx}");
    }
    if let Some(v) = e.get("reason").and_then(J::as_str) {
        assert_eq!(o.reason.as_deref(), Some(v), "reason {ctx}");
    }
    if let Some(v) = e.get("head_anchored").and_then(J::as_bool) {
        assert_eq!(o.head_anchored, Some(v), "head_anchored {ctx}");
    }
    if let Some(v) = e.get("elided") {
        assert_eq!(o.elided, strs(v), "elided {ctx}");
    }
    for w in strs(e.get("warnings").unwrap_or(&J::Null)) {
        assert!(o.warnings.contains(&w), "warning {w} missing: {ctx}");
    }
    for w in strs(e.get("ignored").unwrap_or(&J::Null)) {
        assert!(o.ignored.contains(&w), "ignored {w} missing: {ctx}");
    }
    if let Some(v) = e.get("witnesses") {
        assert_eq!(o.witnesses, strs(v), "witnesses {ctx}");
    }
    if let Some(v) = e.get("records_after_head").and_then(J::as_u64) {
        assert_eq!(o.records_after_head, Some(v), "records_after_head {ctx}");
    }
    if let Some(v) = e.get("trust_path") {
        assert_eq!(o.trust_path, strs(v), "trust_path {ctx}");
    }
    if let Some(v) = e.get("authentication").and_then(J::as_str) {
        assert_eq!(o.authentication.as_deref(), Some(v), "authentication {ctx}");
    }
    if let Some(v) = e.get("error").and_then(J::as_str) {
        if !o.error.is_empty() && v.starts_with("Checkpoint") {
            assert!(o.error.contains(v), "error {v}: {ctx}");
        }
    }
}

#[test]
fn every_run_through_the_library() {
    let mut runs = 0;
    for dir in all_vectors() {
        let inp = inputs(&dir);
        let name = dir.file_name().unwrap().to_string_lossy().into_owned();
        for r in inp["runs"].as_array().unwrap() {
            let cmd = r["command"].as_str().unwrap();
            if matches!(cmd, "ed25519" | "checkpoint-compare") {
                continue;
            }
            runs += 1;
            let o = run_library(&dir, r);
            check(&name, r, &o);
        }
    }
    assert!(runs >= 100, "only {runs} runs");
}

#[test]
fn ed25519_edge_cases() {
    let dir = vectors_dir().join("ed25519-edge");
    let cases: J =
        serde_json::from_str(&std::fs::read_to_string(dir.join("cases.json")).unwrap()).unwrap();
    let expected: J =
        serde_json::from_str(&std::fs::read_to_string(dir.join("expected.json")).unwrap()).unwrap();
    for (c, e) in cases
        .as_array()
        .unwrap()
        .iter()
        .zip(expected.as_array().unwrap())
    {
        let pk: [u8; 32] = unhex(c["pub_key"].as_str().unwrap()).unwrap();
        let sig: [u8; 64] = unhex(c["signature"].as_str().unwrap()).unwrap();
        let msg = hex_decode(c["message"].as_str().unwrap());
        let got = ed25519::verify(&pk, &msg, &sig);
        assert_eq!(
            got.is_ok(),
            e["accept"].as_bool().unwrap(),
            "case {}",
            e["case"]
        );
        if let Err(f) = got {
            assert_eq!(
                f.reason(),
                e["reason"].as_str().unwrap(),
                "case {}",
                e["case"]
            );
        }
    }
}

fn hex_decode(s: &str) -> Vec<u8> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn appendix_a_fingerprints() {
    let inp = inputs(&vectors_dir().join("pin-weak-key"));
    for e in inp["appendix_a"].as_array().unwrap() {
        let k: [u8; 32] = unhex(e["encoding"].as_str().unwrap()).unwrap();
        let pk = PublicKey::ed25519(k);
        assert_eq!(
            pk.fingerprint().to_hex(),
            e["fingerprint"].as_str().unwrap()
        );
        assert!(!pk.is_strong());
    }
}

#[test]
fn checkpoint_compare_vector() {
    let dir = vectors_dir().join("equivocation");
    let read = |p: &str| std::fs::read(dir.join(p)).unwrap();
    let r = ogentic_audit_core::signed::checkpoint::compare(
        &read("a.json"),
        &read("a.json.sig"),
        &read("b.json"),
        &read("b.json.sig"),
    )
    .unwrap();
    assert!(matches!(
        r,
        ogentic_audit_core::signed::checkpoint::Comparison::Equivocation { .. }
    ));
}

/// The release builder produces the committed attestation for the same
/// inputs, byte for byte (and so the same deterministic signature).
#[test]
fn release_builder_matches_the_clean_vector() {
    let vec_dir = vectors_dir().join("release-clean/release");
    let src_log = vectors_dir().join("signed-release-source/log");
    let tmp = tempfile::tempdir().unwrap();
    let rel = tmp.path();
    for f in [
        "pages/0001.pdf",
        "pages/0002.pdf",
        "doc.pdf",
        "Decisions.csv",
    ] {
        let p = rel.join(f);
        std::fs::create_dir_all(p.parent().unwrap()).unwrap();
        std::fs::copy(vec_dir.join(f), &p).unwrap();
    }
    let mut b = AttestationBuilder::new(rel, "2026-0147");
    b.created_at("2026-10-03T12:00:00.000Z");
    b.add_file(FileSpec::new("pages/0001.pdf").role("page"));
    b.add_file(FileSpec::new("pages/0002.pdf").role("page"));
    b.add_file(FileSpec::new("doc.pdf").role("document"));
    b.add_file(FileSpec::new("Decisions.csv").role("index").parts(vec![
        Part {
            name: "header".into(),
            offset: 0,
            length: 14,
        },
        Part {
            name: "row 1".into(),
            offset: 14,
            length: 10,
        },
        Part {
            name: "row 2".into(),
            offset: 24,
            length: 10,
        },
    ]));
    b.add_log(LogSpec {
        source: src_log,
        path: "Audit log".into(),
        head: None,
        elide: vec![],
    });
    let seed: [u8; 32] =
        unhex("9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60").unwrap();
    let digest = b.write(&InMemorySigner::from_seed(seed)).unwrap();
    for f in [
        "ogentic-audit-release.json",
        "ogentic-audit-release.json.sig",
        "ogentic-audit-signer.pub",
        "HOW-TO-VERIFY.txt",
        "Audit log/audit-0000.cbor",
    ] {
        assert_eq!(
            std::fs::read(rel.join(f)).unwrap(),
            std::fs::read(vec_dir.join(f)).unwrap(),
            "{f}"
        );
    }
    let att = std::fs::read(vec_dir.join("ogentic-audit-release.json")).unwrap();
    assert_eq!(digest.0, <[u8; 32]>::from(Sha256::digest(&att)));
}
